/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.65
 * Generated at: 2022-09-16 10:21:03 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class admin_002ddashboard_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/T:/Tempory%20Data/Web%20App/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/go-cheeta/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153365282000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1660112728163L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005ftag_005fforEach_0026_005fvar_005fitems;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005ftag_005fset_0026_005fvar_005fvalue_005fscope_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005ftag_005fout_0026_005fvalue_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005ftag_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005ftag_005fset_0026_005fvar_005fvalue_005fscope_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005ftag_005fout_0026_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005ftag_005fforEach_0026_005fvar_005fitems.release();
    _005fjspx_005ftagPool_005ftag_005fset_0026_005fvar_005fvalue_005fscope_005fnobody.release();
    _005fjspx_005ftagPool_005ftag_005fout_0026_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write(" \n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("\n");
      out.write("<meta charset=\"ISO-8859-1\">\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\" />\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\" />\n");
      out.write("    <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css\" rel=\"stylesheet\" />\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css\" />\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/addmin-dashboard-side.css\" />\n");
      out.write("  <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js\"></script>\n");
      out.write("<style type=\"text/css\">\n");
      out.write(".tsize{table-layout: auto;\n");
      out.write("  width: 20%;  }\n");
      out.write("\n");
      out.write("tsize tbody tr .td{ font-weight: bold;}\n");
      out.write("\n");
      out.write("tsize thead tr { border: 14pt double(1,12,1) }\n");
      out.write("thead { background: #38AAA4; color:#333A47; }\n");
      out.write(".search{\n");
      out.write("\n");
      out.write("width: 50%;  \n");
      out.write("color:red;\n");
      out.write("display: flex;\n");
      out.write("  flex-wrap: nowrap;\n");
      out.write("  align-items: center;\n");
      out.write("\n");
      out.write("}\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("</style>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("<h1>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${message}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</h1>\n");
      out.write("<div class=\"d-flex\" id=\"wrapper\">\n");
      out.write("\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "admin-dashboard-side.jsp", out, false);
      out.write("\n");
      out.write("<div id=\"page-content-wrapper\">\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "admin-dashboard-header.jsp", out, false);
      out.write("\n");
      out.write(" <div class=\"container-fluid px-4\">\n");
      out.write(" \n");
      out.write(" <div class=\"d-flex justify-content-center\">\n");
      out.write("</div>\n");
      out.write("<h3 style=\"font-weight:bold\">Branch Sales Details</h3>\n");
      out.write("<table class=\"tsize\" id=\"tb1\">\n");
      out.write("<thead>\n");
      out.write("<tr>\n");
      out.write("<th>Branch Name</th>\n");
      out.write("<th>Total</th>\n");
      out.write("\n");
      out.write("</tr>\n");
      out.write("\n");
      out.write("</thead>\n");
      out.write(" <tbody>  \n");
      out.write(" \n");
      out.write(" ");
      if (_jspx_meth_tag_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write(" <tr>\n");
      out.write(" <thead>\n");
      out.write(" <tr>\n");
      out.write("\n");
      out.write("\n");
      out.write(" <th>Total Sale</th>\n");
      out.write("\n");
      out.write("\n");
      out.write(" <th>\n");
      out.write("\n");
      out.write("  ");
      if (_jspx_meth_tag_005fset_005f0(_jspx_page_context))
        return;
      out.write('\n');
      out.write(' ');
      if (_jspx_meth_tag_005fout_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write(" </th>\n");
      out.write(" \n");
      out.write(" </tr>\n");
      out.write(" \n");
      out.write(" \n");
      out.write(" </thead>\n");
      out.write(" \n");
      out.write(" \n");
      out.write("\n");
      out.write("  \n");
      out.write(" </tbody>\n");
      out.write("\n");
      out.write("\n");
      out.write("</table ><br>\n");
      out.write("<form action=\"salesData\" method=\"GET\">\n");
      out.write("<div class=\"search\">\n");
      out.write("<input type=\"hidden\" name=\"action\" value=\"branchtot\">\n");
      out.write("<input type=\"date\"  class=\" txt form-control addvehicle-input\" name=\"date\" id=\"date\" required>\n");
      out.write(" <select class=\"form-select form-group\" aria-label=\"Default select example\" name=\"branch\" id=\"branch\" required>\n");
      out.write("   \n");
      out.write("  <option VALUE=\"\"><b>Select Branch</b></option>\n");
      out.write("  <option value=\"galle\">Galle</option>\n");
      out.write("  <option value=\"kandy\" >Kandy</option>\n");
      out.write("  <option value=\"nugegoda\">Nugegoda</option>\n");
      out.write("  <option value=\"gampaha\">Gampaha</option>\n");
      out.write("  <option value=\"kurunegala\">Kurunegala</option>\n");
      out.write("    <option value=\"jaffna\">Jaffna</option>\n");
      out.write("    </select>\n");
      out.write("<button type=\"submit\" class=\"searchbtn btn btn-light\" onclick=\"hideButton()\" >Search</button> \n");
      out.write("</div>\n");
      out.write(" </form><br>\n");
      out.write("\n");
      out.write("<table class=\"tsize\">\n");
      out.write("<thead>\n");
      out.write(" \n");
      out.write("<tr>\n");
      if (_jspx_meth_tag_005fforEach_005f1(_jspx_page_context))
        return;
      out.write("\n");
      out.write("</tr>\n");
      out.write("\n");
      out.write("</thead>\n");
      out.write("</table>\n");
      out.write("\n");
      out.write("\n");
      out.write("</div>\n");
      out.write("</div>\n");
      out.write(" </div>\n");
      out.write("\n");
      out.write("<div>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${message}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</div>\n");
      out.write("<script type=\"text/javascript\">\n");
      out.write("function hideButton()\n");
      out.write("{\n");
      out.write("	\n");
      out.write("	tb1.style.display = 'none';\n");
      out.write("}\n");
      out.write("\n");
      out.write("\n");
      out.write("</script>\n");
      out.write("\n");
      out.write("<script src=\"javascript/script-dashboard.js\"></script>\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_tag_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  tag:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_tag_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005ftag_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_tag_005fforEach_005f0_reused = false;
    try {
      _jspx_th_tag_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_tag_005fforEach_005f0.setParent(null);
      // /admin-dashboard.jsp(60,1) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_tag_005fforEach_005f0.setVar("sale");
      // /admin-dashboard.jsp(60,1) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_tag_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/admin-dashboard.jsp(60,1) '${saleData}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${saleData}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int[] _jspx_push_body_count_tag_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_tag_005fforEach_005f0 = _jspx_th_tag_005fforEach_005f0.doStartTag();
        if (_jspx_eval_tag_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\n");
            out.write(" \n");
            out.write(" <tr>\n");
            out.write(" <td style=\"font-weight:bold\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sale.getBranch()}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\n");
            out.write(" <td style=\"font-weight:bold\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sale.getPaymentcoast()}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\n");
            out.write(" \n");
            out.write(" </tr>\n");
            out.write("\n");
            out.write("\n");
            out.write(" ");
            int evalDoAfterBody = _jspx_th_tag_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_tag_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_tag_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_tag_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_tag_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005ftag_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_tag_005fforEach_005f0);
      _jspx_th_tag_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_tag_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_tag_005fforEach_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_tag_005fset_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  tag:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_tag_005fset_005f0 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005ftag_005fset_0026_005fvar_005fvalue_005fscope_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_tag_005fset_005f0_reused = false;
    try {
      _jspx_th_tag_005fset_005f0.setPageContext(_jspx_page_context);
      _jspx_th_tag_005fset_005f0.setParent(null);
      // /admin-dashboard.jsp(80,2) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_tag_005fset_005f0.setVar("total");
      // /admin-dashboard.jsp(80,2) name = scope type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_tag_005fset_005f0.setScope("session");
      // /admin-dashboard.jsp(80,2) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_tag_005fset_005f0.setValue(new org.apache.jasper.el.JspValueExpression("/admin-dashboard.jsp(80,2) '${tot}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${tot}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int _jspx_eval_tag_005fset_005f0 = _jspx_th_tag_005fset_005f0.doStartTag();
      if (_jspx_th_tag_005fset_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005ftag_005fset_0026_005fvar_005fvalue_005fscope_005fnobody.reuse(_jspx_th_tag_005fset_005f0);
      _jspx_th_tag_005fset_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_tag_005fset_005f0, _jsp_getInstanceManager(), _jspx_th_tag_005fset_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_tag_005fout_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  tag:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_tag_005fout_005f0 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005ftag_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    boolean _jspx_th_tag_005fout_005f0_reused = false;
    try {
      _jspx_th_tag_005fout_005f0.setPageContext(_jspx_page_context);
      _jspx_th_tag_005fout_005f0.setParent(null);
      // /admin-dashboard.jsp(81,1) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_tag_005fout_005f0.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${total.getPaymentcoast()}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int _jspx_eval_tag_005fout_005f0 = _jspx_th_tag_005fout_005f0.doStartTag();
      if (_jspx_th_tag_005fout_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005ftag_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_tag_005fout_005f0);
      _jspx_th_tag_005fout_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_tag_005fout_005f0, _jsp_getInstanceManager(), _jspx_th_tag_005fout_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_tag_005fforEach_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  tag:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_tag_005fforEach_005f1 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005ftag_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_tag_005fforEach_005f1_reused = false;
    try {
      _jspx_th_tag_005fforEach_005f1.setPageContext(_jspx_page_context);
      _jspx_th_tag_005fforEach_005f1.setParent(null);
      // /admin-dashboard.jsp(118,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_tag_005fforEach_005f1.setVar("searchtotal");
      // /admin-dashboard.jsp(118,0) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_tag_005fforEach_005f1.setItems(new org.apache.jasper.el.JspValueExpression("/admin-dashboard.jsp(118,0) '${branchsearch}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${branchsearch}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int[] _jspx_push_body_count_tag_005fforEach_005f1 = new int[] { 0 };
      try {
        int _jspx_eval_tag_005fforEach_005f1 = _jspx_th_tag_005fforEach_005f1.doStartTag();
        if (_jspx_eval_tag_005fforEach_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\n");
            out.write("\n");
            out.write("<th>Total</th>\n");
            out.write("<th>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${searchtotal.getPaymentcoast()}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</th>\n");
            int evalDoAfterBody = _jspx_th_tag_005fforEach_005f1.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_tag_005fforEach_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_tag_005fforEach_005f1[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_tag_005fforEach_005f1.doCatch(_jspx_exception);
      } finally {
        _jspx_th_tag_005fforEach_005f1.doFinally();
      }
      _005fjspx_005ftagPool_005ftag_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_tag_005fforEach_005f1);
      _jspx_th_tag_005fforEach_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_tag_005fforEach_005f1, _jsp_getInstanceManager(), _jspx_th_tag_005fforEach_005f1_reused);
    }
    return false;
  }
}
