/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.65
 * Generated at: 2022-08-21 20:24:00 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class admin_002dupdate_002dvehicle_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/T:/Tempory%20Data/Web%20App/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/go-cheeta/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153365282000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1660112728163L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005ftag_005fset_0026_005fvar_005fvalue_005fscope_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005ftag_005fif_0026_005ftest;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005ftag_005fset_0026_005fvar_005fvalue_005fscope_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005ftag_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005ftag_005fset_0026_005fvar_005fvalue_005fscope_005fnobody.release();
    _005fjspx_005ftagPool_005ftag_005fif_0026_005ftest.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write(" \r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"ISO-8859-1\">\r\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\" />\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\" />\r\n");
      out.write("    <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css\" rel=\"stylesheet\" />\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css\" />\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/addmin-dashboard-side.css\" />\r\n");
      out.write("  <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div class=\"d-flex\" id=\"wrapper\">\r\n");
      out.write("\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "admin-dashboard-side.jsp", out, false);
      out.write("\r\n");
      out.write("<div id=\"page-content-wrapper\">\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "admin-dashboard-header.jsp", out, false);
      out.write("\r\n");
      out.write(" <div class=\"container-fluid px-4\">\r\n");
      out.write(" <div class=\"d-flex justify-content-center\">\r\n");
      if (_jspx_meth_tag_005fset_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\r\n");
      out.write("<form class=\"addvehicle-formdiv\" action=\"updateVehicle\" method=\"post\" >\r\n");
      out.write("<div class=\"form-group \">\r\n");
      out.write("    \r\n");
      out.write("      <div class=\"form-group \">\r\n");
      out.write("    <input type=\"text\" class=\"form-control addvehicle-input\" name=\"register_Number\" id=\"\" placeholder=\"Vehicle Register Number\" value=\" ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${vehicle.getVehicle_Registernumber()}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" required>\r\n");
      out.write("  </div><br></div>\r\n");
      out.write("  <div class=\"form-group\">\r\n");
      out.write("    <input type=\"text\" class=\"form-control addvehicle-input\" name=\"vehicle_Model\" id=\"\" placeholder=\"Vehicle Model\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${vehicle.getVehicle_Model()}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"  required></div><br>\r\n");
      out.write("    <div class=\"form-group \">\r\n");
      out.write("    <input type=\"number\" min=\"2\" class=\"form-control addvehicle-input\" name=\"vehicle_Seat\" id=\"\" placeholder=\"Vehicle Seat\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${vehicle.getNumberof_Seat()}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"  required>\r\n");
      out.write("  </div><br><input type=\"hidden\" name=\"vehicleID\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${vehicle.getVehicleID()}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"> \r\n");
      out.write("   <div class=\"form-group \">\r\n");
      out.write("    <input type=\"number\" min=\"1000\" class=\"form-control addvehicle-input\" name=\"costPer_Km\" id=\"\" placeholder=\"Coast Per Km\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${vehicle.getCostper_Km()}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"  required>\r\n");
      out.write("  </div><br>\r\n");
      out.write("  <div class=\"form-group \" >\r\n");
      out.write(" \r\n");
      out.write(" <select class=\"form-select\" aria-label=\"Default select example\" name=\"vehicle_type\" required>\r\n");
      out.write(" ");
      if (_jspx_meth_tag_005fset_005f1(_jspx_page_context))
        return;
      out.write('\r');
      out.write('\n');
      out.write(' ');
      if (_jspx_meth_tag_005fif_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("   ");
      if (_jspx_meth_tag_005fif_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("    ");
      if (_jspx_meth_tag_005fif_005f2(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("  </select><br/>\r\n");
      out.write(" \r\n");
      out.write("\r\n");
      out.write("   ");
      if (_jspx_meth_tag_005fset_005f2(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("  \r\n");
      out.write("   <select class=\"form-select form-group\" aria-label=\"Default select example\" name=\"branch\" required>\r\n");
      out.write("    ");
      if (_jspx_meth_tag_005fif_005f3(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("       ");
      if (_jspx_meth_tag_005fif_005f4(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("       ");
      if (_jspx_meth_tag_005fif_005f5(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("       ");
      if (_jspx_meth_tag_005fif_005f6(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("       ");
      if (_jspx_meth_tag_005fif_005f7(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("       ");
      if (_jspx_meth_tag_005fif_005f8(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("         ");
      if (_jspx_meth_tag_005fif_005f9(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("</select>\r\n");
      out.write(" \r\n");
      out.write("  </div><br>\r\n");
      out.write("    \r\n");
      out.write("    <div class=\"d-flex justify-content-center\">\r\n");
      out.write("    <input type=\"hidden\" name=\"action\" value=\"updateVehicle\"/>\r\n");
      out.write("   <button type=\"submit\" class=\"btn btn-success addvehiclebtn\">Update Vehicle</button>\r\n");
      out.write("    </div>\r\n");
      out.write("  </form>\r\n");
      out.write("  <p>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${message}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</p>\r\n");
      out.write("  </div>\r\n");
      out.write(" </div>\r\n");
      out.write("</div>\r\n");
      out.write(" </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<script src=\"javascript/script-dashboard.js\"></script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_tag_005fset_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  tag:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_tag_005fset_005f0 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005ftag_005fset_0026_005fvar_005fvalue_005fscope_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_tag_005fset_005f0_reused = false;
    try {
      _jspx_th_tag_005fset_005f0.setPageContext(_jspx_page_context);
      _jspx_th_tag_005fset_005f0.setParent(null);
      // /admin-update-vehicle.jsp(24,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_tag_005fset_005f0.setVar("vehicle");
      // /admin-update-vehicle.jsp(24,0) name = scope type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_tag_005fset_005f0.setScope("session");
      // /admin-update-vehicle.jsp(24,0) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_tag_005fset_005f0.setValue(new org.apache.jasper.el.JspValueExpression("/admin-update-vehicle.jsp(24,0) '${vehicle}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${vehicle}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int _jspx_eval_tag_005fset_005f0 = _jspx_th_tag_005fset_005f0.doStartTag();
      if (_jspx_th_tag_005fset_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005ftag_005fset_0026_005fvar_005fvalue_005fscope_005fnobody.reuse(_jspx_th_tag_005fset_005f0);
      _jspx_th_tag_005fset_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_tag_005fset_005f0, _jsp_getInstanceManager(), _jspx_th_tag_005fset_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_tag_005fset_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  tag:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_tag_005fset_005f1 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005ftag_005fset_0026_005fvar_005fvalue_005fscope_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_tag_005fset_005f1_reused = false;
    try {
      _jspx_th_tag_005fset_005f1.setPageContext(_jspx_page_context);
      _jspx_th_tag_005fset_005f1.setParent(null);
      // /admin-update-vehicle.jsp(43,1) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_tag_005fset_005f1.setVar("vehicletype");
      // /admin-update-vehicle.jsp(43,1) name = scope type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_tag_005fset_005f1.setScope("session");
      // /admin-update-vehicle.jsp(43,1) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_tag_005fset_005f1.setValue(new org.apache.jasper.el.JspValueExpression("/admin-update-vehicle.jsp(43,1) '${vehicle.getVehicle_Type()}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${vehicle.getVehicle_Type()}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int _jspx_eval_tag_005fset_005f1 = _jspx_th_tag_005fset_005f1.doStartTag();
      if (_jspx_th_tag_005fset_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005ftag_005fset_0026_005fvar_005fvalue_005fscope_005fnobody.reuse(_jspx_th_tag_005fset_005f1);
      _jspx_th_tag_005fset_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_tag_005fset_005f1, _jsp_getInstanceManager(), _jspx_th_tag_005fset_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_tag_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  tag:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_tag_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005ftag_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_tag_005fif_005f0_reused = false;
    try {
      _jspx_th_tag_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_tag_005fif_005f0.setParent(null);
      // /admin-update-vehicle.jsp(44,1) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_tag_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${vehicletype=='car'}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_tag_005fif_005f0 = _jspx_th_tag_005fif_005f0.doStartTag();
      if (_jspx_eval_tag_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("  <option VALUE=\"\"><b>Select Vehicle Type</b></option>\r\n");
          out.write("  <option value=\"car\" selected>Car</option>\r\n");
          out.write("  <option value=\"van\">Van</option>\r\n");
          out.write("  <option value=\"bus\">Bus</option>\r\n");
          out.write("  ");
          int evalDoAfterBody = _jspx_th_tag_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_tag_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005ftag_005fif_0026_005ftest.reuse(_jspx_th_tag_005fif_005f0);
      _jspx_th_tag_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_tag_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_tag_005fif_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_tag_005fif_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  tag:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_tag_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005ftag_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_tag_005fif_005f1_reused = false;
    try {
      _jspx_th_tag_005fif_005f1.setPageContext(_jspx_page_context);
      _jspx_th_tag_005fif_005f1.setParent(null);
      // /admin-update-vehicle.jsp(50,3) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_tag_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${vehicletype=='van'}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_tag_005fif_005f1 = _jspx_th_tag_005fif_005f1.doStartTag();
      if (_jspx_eval_tag_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("  <option VALUE=\"\"><b>Select Vehicle Type</b></option>\r\n");
          out.write("  <option value=\"car\">Car</option>\r\n");
          out.write("  <option value=\"van\" selected>Van</option>\r\n");
          out.write("  <option value=\"bus\">Bus</option>\r\n");
          out.write("  ");
          int evalDoAfterBody = _jspx_th_tag_005fif_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_tag_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005ftag_005fif_0026_005ftest.reuse(_jspx_th_tag_005fif_005f1);
      _jspx_th_tag_005fif_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_tag_005fif_005f1, _jsp_getInstanceManager(), _jspx_th_tag_005fif_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_tag_005fif_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  tag:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_tag_005fif_005f2 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005ftag_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_tag_005fif_005f2_reused = false;
    try {
      _jspx_th_tag_005fif_005f2.setPageContext(_jspx_page_context);
      _jspx_th_tag_005fif_005f2.setParent(null);
      // /admin-update-vehicle.jsp(56,4) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_tag_005fif_005f2.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${vehicletype=='bus'}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_tag_005fif_005f2 = _jspx_th_tag_005fif_005f2.doStartTag();
      if (_jspx_eval_tag_005fif_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("  <option VALUE=\"\"><b>Select Vehicle Type</b></option>\r\n");
          out.write("  <option value=\"car\">Car</option>\r\n");
          out.write("  <option value=\"van\">Van</option>\r\n");
          out.write("  <option value=\"bus\" selected>Bus</option>\r\n");
          out.write("  ");
          int evalDoAfterBody = _jspx_th_tag_005fif_005f2.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_tag_005fif_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005ftag_005fif_0026_005ftest.reuse(_jspx_th_tag_005fif_005f2);
      _jspx_th_tag_005fif_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_tag_005fif_005f2, _jsp_getInstanceManager(), _jspx_th_tag_005fif_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_tag_005fset_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  tag:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_tag_005fset_005f2 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005ftag_005fset_0026_005fvar_005fvalue_005fscope_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_tag_005fset_005f2_reused = false;
    try {
      _jspx_th_tag_005fset_005f2.setPageContext(_jspx_page_context);
      _jspx_th_tag_005fset_005f2.setParent(null);
      // /admin-update-vehicle.jsp(65,3) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_tag_005fset_005f2.setVar("vehiclebranch");
      // /admin-update-vehicle.jsp(65,3) name = scope type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_tag_005fset_005f2.setScope("session");
      // /admin-update-vehicle.jsp(65,3) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_tag_005fset_005f2.setValue(new org.apache.jasper.el.JspValueExpression("/admin-update-vehicle.jsp(65,3) '${vehicle.getBranch()}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${vehicle.getBranch()}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int _jspx_eval_tag_005fset_005f2 = _jspx_th_tag_005fset_005f2.doStartTag();
      if (_jspx_th_tag_005fset_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005ftag_005fset_0026_005fvar_005fvalue_005fscope_005fnobody.reuse(_jspx_th_tag_005fset_005f2);
      _jspx_th_tag_005fset_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_tag_005fset_005f2, _jsp_getInstanceManager(), _jspx_th_tag_005fset_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_tag_005fif_005f3(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  tag:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_tag_005fif_005f3 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005ftag_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_tag_005fif_005f3_reused = false;
    try {
      _jspx_th_tag_005fif_005f3.setPageContext(_jspx_page_context);
      _jspx_th_tag_005fif_005f3.setParent(null);
      // /admin-update-vehicle.jsp(68,4) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_tag_005fif_005f3.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${vehiclebranch=='kandy'}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_tag_005fif_005f3 = _jspx_th_tag_005fif_005f3.doStartTag();
      if (_jspx_eval_tag_005fif_005f3 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("  <option VALUE=\"\"><b>Select Branch</b></option>\r\n");
          out.write("  <option value=\"galle\">Galle</option>\r\n");
          out.write("  <option value=\"kandy\" selected>Kandy</option>\r\n");
          out.write("  <option value=\"nugegoda\">Nugegoda</option>\r\n");
          out.write("  <option value=\"gampaha\">Gampaha</option>\r\n");
          out.write("  <option value=\"kurunegala\">Kurunegala</option>\r\n");
          out.write("    <option value=\"jaffna\">Jaffna</option>\r\n");
          out.write("    ");
          int evalDoAfterBody = _jspx_th_tag_005fif_005f3.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_tag_005fif_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005ftag_005fif_0026_005ftest.reuse(_jspx_th_tag_005fif_005f3);
      _jspx_th_tag_005fif_005f3_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_tag_005fif_005f3, _jsp_getInstanceManager(), _jspx_th_tag_005fif_005f3_reused);
    }
    return false;
  }

  private boolean _jspx_meth_tag_005fif_005f4(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  tag:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_tag_005fif_005f4 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005ftag_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_tag_005fif_005f4_reused = false;
    try {
      _jspx_th_tag_005fif_005f4.setPageContext(_jspx_page_context);
      _jspx_th_tag_005fif_005f4.setParent(null);
      // /admin-update-vehicle.jsp(77,7) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_tag_005fif_005f4.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${vehiclebranch=='galle'}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_tag_005fif_005f4 = _jspx_th_tag_005fif_005f4.doStartTag();
      if (_jspx_eval_tag_005fif_005f4 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("  <option VALUE=\"\"><b>Select Branch</b></option>\r\n");
          out.write("  <option value=\"galle\" selected>Galle</option>\r\n");
          out.write("  <option value=\"kandy\" >Kandy</option>\r\n");
          out.write("  <option value=\"nugegoda\">Nugegoda</option>\r\n");
          out.write("  <option value=\"gampaha\">Gampaha</option>\r\n");
          out.write("  <option value=\"kurunegala\">Kurunegala</option>\r\n");
          out.write("    <option value=\"jaffna\">Jaffna</option>\r\n");
          out.write("    ");
          int evalDoAfterBody = _jspx_th_tag_005fif_005f4.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_tag_005fif_005f4.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005ftag_005fif_0026_005ftest.reuse(_jspx_th_tag_005fif_005f4);
      _jspx_th_tag_005fif_005f4_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_tag_005fif_005f4, _jsp_getInstanceManager(), _jspx_th_tag_005fif_005f4_reused);
    }
    return false;
  }

  private boolean _jspx_meth_tag_005fif_005f5(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  tag:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_tag_005fif_005f5 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005ftag_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_tag_005fif_005f5_reused = false;
    try {
      _jspx_th_tag_005fif_005f5.setPageContext(_jspx_page_context);
      _jspx_th_tag_005fif_005f5.setParent(null);
      // /admin-update-vehicle.jsp(86,7) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_tag_005fif_005f5.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${vehiclebranch=='nugegoda'}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_tag_005fif_005f5 = _jspx_th_tag_005fif_005f5.doStartTag();
      if (_jspx_eval_tag_005fif_005f5 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("  <option VALUE=\"\"><b>Select Branch</b></option>\r\n");
          out.write("  <option value=\"galle\">Galle</option>\r\n");
          out.write("  <option value=\"kandy\" >Kandy</option>\r\n");
          out.write("  <option value=\"nugegoda\" selected>Nugegoda</option>\r\n");
          out.write("  <option value=\"gampaha\">Gampaha</option>\r\n");
          out.write("  <option value=\"kurunegala\">Kurunegala</option>\r\n");
          out.write("    <option value=\"jaffna\">Jaffna</option>\r\n");
          out.write("    ");
          int evalDoAfterBody = _jspx_th_tag_005fif_005f5.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_tag_005fif_005f5.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005ftag_005fif_0026_005ftest.reuse(_jspx_th_tag_005fif_005f5);
      _jspx_th_tag_005fif_005f5_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_tag_005fif_005f5, _jsp_getInstanceManager(), _jspx_th_tag_005fif_005f5_reused);
    }
    return false;
  }

  private boolean _jspx_meth_tag_005fif_005f6(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  tag:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_tag_005fif_005f6 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005ftag_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_tag_005fif_005f6_reused = false;
    try {
      _jspx_th_tag_005fif_005f6.setPageContext(_jspx_page_context);
      _jspx_th_tag_005fif_005f6.setParent(null);
      // /admin-update-vehicle.jsp(95,7) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_tag_005fif_005f6.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${vehiclebranch=='gampaha'}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_tag_005fif_005f6 = _jspx_th_tag_005fif_005f6.doStartTag();
      if (_jspx_eval_tag_005fif_005f6 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("  <option VALUE=\"\"><b>Select Branch</b></option>\r\n");
          out.write("  <option value=\"galle\">Galle</option>\r\n");
          out.write("  <option value=\"kandy\" >Kandy</option>\r\n");
          out.write("  <option value=\"nugegoda\">Nugegoda</option>\r\n");
          out.write("  <option value=\"gampaha\" selected>Gampaha</option>\r\n");
          out.write("  <option value=\"kurunegala\">Kurunegala</option>\r\n");
          out.write("    <option value=\"jaffna\">Jaffna</option>\r\n");
          out.write("    ");
          int evalDoAfterBody = _jspx_th_tag_005fif_005f6.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_tag_005fif_005f6.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005ftag_005fif_0026_005ftest.reuse(_jspx_th_tag_005fif_005f6);
      _jspx_th_tag_005fif_005f6_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_tag_005fif_005f6, _jsp_getInstanceManager(), _jspx_th_tag_005fif_005f6_reused);
    }
    return false;
  }

  private boolean _jspx_meth_tag_005fif_005f7(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  tag:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_tag_005fif_005f7 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005ftag_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_tag_005fif_005f7_reused = false;
    try {
      _jspx_th_tag_005fif_005f7.setPageContext(_jspx_page_context);
      _jspx_th_tag_005fif_005f7.setParent(null);
      // /admin-update-vehicle.jsp(104,7) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_tag_005fif_005f7.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${vehiclebranch=='kurunegala'}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_tag_005fif_005f7 = _jspx_th_tag_005fif_005f7.doStartTag();
      if (_jspx_eval_tag_005fif_005f7 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("  <option VALUE=\"\"><b>Select Branch</b></option>\r\n");
          out.write("  <option value=\"galle\">Galle</option>\r\n");
          out.write("  <option value=\"kandy\" >Kandy</option>\r\n");
          out.write("  <option value=\"nugegoda\">Nugegoda</option>\r\n");
          out.write("  <option value=\"gampaha\">Gampaha</option>\r\n");
          out.write("  <option value=\"kurunegala\" selected>Kurunegala</option>\r\n");
          out.write("    <option value=\"jaffna\">Jaffna</option>\r\n");
          out.write("    ");
          int evalDoAfterBody = _jspx_th_tag_005fif_005f7.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_tag_005fif_005f7.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005ftag_005fif_0026_005ftest.reuse(_jspx_th_tag_005fif_005f7);
      _jspx_th_tag_005fif_005f7_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_tag_005fif_005f7, _jsp_getInstanceManager(), _jspx_th_tag_005fif_005f7_reused);
    }
    return false;
  }

  private boolean _jspx_meth_tag_005fif_005f8(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  tag:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_tag_005fif_005f8 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005ftag_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_tag_005fif_005f8_reused = false;
    try {
      _jspx_th_tag_005fif_005f8.setPageContext(_jspx_page_context);
      _jspx_th_tag_005fif_005f8.setParent(null);
      // /admin-update-vehicle.jsp(113,7) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_tag_005fif_005f8.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${vehiclebranch=='jaffna'}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_tag_005fif_005f8 = _jspx_th_tag_005fif_005f8.doStartTag();
      if (_jspx_eval_tag_005fif_005f8 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("  <option VALUE=\"\"><b>Select Branch</b></option>\r\n");
          out.write("  <option value=\"galle\">Galle</option>\r\n");
          out.write("  <option value=\"kandy\" >Kandy</option>\r\n");
          out.write("  <option value=\"nugegoda\">Nugegoda</option>\r\n");
          out.write("  <option value=\"gampaha\">Gampaha</option>\r\n");
          out.write("  <option value=\"kurunegala\">Kurunegala</option>\r\n");
          out.write("    <option value=\"jaffna\" selected>Jaffna</option>\r\n");
          out.write("    ");
          int evalDoAfterBody = _jspx_th_tag_005fif_005f8.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_tag_005fif_005f8.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005ftag_005fif_0026_005ftest.reuse(_jspx_th_tag_005fif_005f8);
      _jspx_th_tag_005fif_005f8_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_tag_005fif_005f8, _jsp_getInstanceManager(), _jspx_th_tag_005fif_005f8_reused);
    }
    return false;
  }

  private boolean _jspx_meth_tag_005fif_005f9(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  tag:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_tag_005fif_005f9 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005ftag_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_tag_005fif_005f9_reused = false;
    try {
      _jspx_th_tag_005fif_005f9.setPageContext(_jspx_page_context);
      _jspx_th_tag_005fif_005f9.setParent(null);
      // /admin-update-vehicle.jsp(122,9) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_tag_005fif_005f9.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${vehiclebranch==''}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_tag_005fif_005f9 = _jspx_th_tag_005fif_005f9.doStartTag();
      if (_jspx_eval_tag_005fif_005f9 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("  <option VALUE=\"\" selected><b>Select Branch</b></option>\r\n");
          out.write("  <option value=\"galle\">Galle</option>\r\n");
          out.write("  <option value=\"kandy\" >Kandy</option>\r\n");
          out.write("  <option value=\"nugegoda\">Nugegoda</option>\r\n");
          out.write("  <option value=\"gampaha\">Gampaha</option>\r\n");
          out.write("  <option value=\"kurunegala\">Kurunegala</option>\r\n");
          out.write("    <option value=\"jaffna\">Jaffna</option>\r\n");
          out.write("    ");
          int evalDoAfterBody = _jspx_th_tag_005fif_005f9.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_tag_005fif_005f9.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005ftag_005fif_0026_005ftest.reuse(_jspx_th_tag_005fif_005f9);
      _jspx_th_tag_005fif_005f9_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_tag_005fif_005f9, _jsp_getInstanceManager(), _jspx_th_tag_005fif_005f9_reused);
    }
    return false;
  }
}
