/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.65
 * Generated at: 2022-09-19 09:41:35 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class available_002dvehicle_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/T:/Tempory%20Data/Web%20App/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/go-cheeta/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153365282000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1660112728163L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005ftag_005fforEach_0026_005fvar_005fitems;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005ftag_005fset_0026_005fvar_005fvalue_005fscope_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005ftag_005fif_0026_005ftest;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005ftag_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005ftag_005fset_0026_005fvar_005fvalue_005fscope_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005ftag_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005ftag_005fforEach_0026_005fvar_005fitems.release();
    _005fjspx_005ftagPool_005ftag_005fset_0026_005fvar_005fvalue_005fscope_005fnobody.release();
    _005fjspx_005ftagPool_005ftag_005fif_0026_005ftest.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write(" \n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta charset=\"ISO-8859-1\">\n");
      out.write("    <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css\" rel=\"stylesheet\"/>\n");
      out.write("     <link rel=\"stylesheet\" href=\"css/addmin-dashboard-side.css\" />\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\" />\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css\"/>\n");
      out.write("\n");
      out.write("<link rel=\"stylesheet\" href=\"css/booking-style.css\" />\n");
      out.write("<style>\n");
      out.write("body{\n");
      out.write("       background-image: url(\"image/bookingbg.jpeg\");\n");
      out.write("       background-size: auto; \n");
      out.write("        background-repeat: repeat;\n");
      out.write("       \n");
      out.write("       \n");
      out.write("       }\n");
      out.write("       \n");
      out.write("       \n");
      out.write("       \n");
      out.write(".fstrow .form-group{\n");
      out.write("    Display:flex;\n");
      out.write("    \n");
      out.write("    \n");
      out.write(" } \n");
      out.write(" .fstrow .form-group input{\n");
      out.write("    margin: 10px;\n");
      out.write("   \n");
      out.write("    \n");
      out.write(" }\n");
      out.write("  .fstrow .form-group  input{\n");
      out.write("  color:red;\n");
      out.write("  font-weight:bold;\n");
      out.write("  width:200%;\n");
      out.write("  }\n");
      out.write(" \n");
      out.write(" .cent{\n");
      out.write(" \n");
      out.write(" padding-top:50px;\n");
      out.write(" \n");
      out.write(" \n");
      out.write(" }\n");
      out.write("   \n");
      out.write("   .searchbtn{\n");
      out.write("      margin: 10px;\n");
      out.write("      width:100%;\n");
      out.write("      height:100%;\n");
      out.write("   }\n");
      out.write("   \n");
      out.write("  .mt-100{\n");
      out.write("margin-top: 100px;\n");
      out.write("}\n");
      out.write(".card {\n");
      out.write("    border-radius: 7px !important;\n");
      out.write("    border-color: #e1e7ec;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".mb-30 {\n");
      out.write("    margin-bottom: 30px !important;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".card-img-tiles {\n");
      out.write("    display: block;\n");
      out.write("    border-bottom: 1px solid #e1e7ec;\n");
      out.write("}\n");
      out.write("\n");
      out.write("a {\n");
      out.write("    color: #0da9ef;\n");
      out.write("    text-decoration: none !important;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".card-img-tiles>.inner {\n");
      out.write("    display: table;\n");
      out.write("    width: 100%;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".card-img-tiles .main-img, .card-img-tiles .thumblist {\n");
      out.write("    display: table-cell;\n");
      out.write("    width: 65%;\n");
      out.write("    padding: 15px;\n");
      out.write("    vertical-align: middle;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".card-img-tiles .main-img>img:last-child, .card-img-tiles .thumblist>img:last-child {\n");
      out.write("    margin-bottom: 0;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".card-img-tiles .main-img>img, .card-img-tiles .thumblist>img {\n");
      out.write("    display: block;\n");
      out.write("    width: 100%;\n");
      out.write("    margin-bottom: 6px;\n");
      out.write("}\n");
      out.write(".thumblist {\n");
      out.write("    width: 35%;\n");
      out.write("    border-left: 1px solid #e1e7ec !important;\n");
      out.write("    display: table-cell;\n");
      out.write("    width: 65%;\n");
      out.write("    padding: 15px;\n");
      out.write("    vertical-align: middle;\n");
      out.write("}\n");
      out.write("\n");
      out.write("\n");
      out.write(".type{ width: 100%;\n");
      out.write("   \n");
      out.write("}\n");
      out.write(".card-img-tiles .thumblist>img {\n");
      out.write("    display: block;\n");
      out.write("    width: 100%;\n");
      out.write("    margin-bottom: 6px;\n");
      out.write("}\n");
      out.write(".btn-group-sm>.btn, .btn-sm {\n");
      out.write("    padding: .45rem .5rem !important;\n");
      out.write("    font-size: .875rem;\n");
      out.write("    line-height: 1.5;\n");
      out.write("    border-radius: .2rem;\n");
      out.write("}\n");
      out.write(".cb{\n");
      out.write("background-color:#343D4C;\n");
      out.write("font-weight:bold;\n");
      out.write("color:white;\n");
      out.write("}\n");
      out.write("\n");
      out.write("	.x{\n");
      out.write("\n");
      out.write("			font-weight: bold;\n");
      out.write("			padding-left: 10px;\n");
      out.write("		}\n");
      out.write("</style>\n");
      out.write("\n");
      out.write("<title>Available Vehicle</title>\n");
      out.write("</head>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<body>\n");


if((String) session.getAttribute("user")==null){
	
	response.sendRedirect("customer-login.jsp");
}

      out.write('\n');
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "customer-navbar.jsp", out, false);
      out.write("\n");
      out.write(" \n");
      out.write("<div class=\"d-flex justify-content-center cent\">\n");
      out.write(" <p>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${message}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</p>\n");
      out.write("\n");
      out.write("<form action=\"availableVehicleDisplay\" method=\"post\">\n");
      out.write("<input type=\"hidden\" name=\"action\" value=\"availableVehicles\"/>\n");
      out.write("\n");
      out.write("<div class=\"fstrow\">\n");
      out.write("<div class=\"form-group\">\n");
      out.write("<input type=\"date\"  class=\" txt form-control addvehicle-input\" name=\"startdate\" id=\"startdate\"  required>\n");
      out.write("<input type=\"date\"  class=\" txt form-control addvehicle-input\" name=\"enddate\" id=\"enddate\"   required>\n");
      out.write("<select class=\"type form-select addvehicle-input\" aria-label=\"Default select example\" name=\"vehicle_type\" required>\n");
      out.write("  <option VALUE=\"\">Type</option>\n");
      out.write("  <option value=\"car\">Car</option>\n");
      out.write("  <option value=\"van\">Van</option>\n");
      out.write("  <option value=\"bus\">Bus</option>\n");
      out.write("</select>\n");
      out.write("\n");
      out.write(" <button type=\"submit\" class=\"searchbtn btn btn-light\" >SEARCH</button> \n");
      out.write("</div>\n");
      out.write("<!-- --> \n");
      out.write("</div>\n");
      out.write("\n");
      out.write("</form>\n");
      out.write("\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("<div class=\"container mt-100\">\n");
      out.write("                            		\n");
      out.write("\n");
      out.write("                        	\n");
      out.write("                               \n");
      out.write("<div class=\"row\">\n");
      out.write(" ");
      if (_jspx_meth_tag_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("        </div>\n");
      out.write("     \n");
      out.write("        </div>\n");
      out.write("<script>\n");
      out.write(" startdate.min = new Date().toISOString().split(\"T\")[0];\n");
      out.write(" \n");
      out.write(" \n");
      out.write("\n");
      out.write("</script>\n");
      out.write("<script type=\"text/javascript\">\n");
      out.write("\n");
      out.write("enddate.min = new Date().toISOString().split(\"T\")[0];\n");
      out.write("</script>\n");
      out.write("</body>\n");
      out.write("\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_tag_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  tag:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_tag_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005ftag_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_tag_005fforEach_005f0_reused = false;
    try {
      _jspx_th_tag_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_tag_005fforEach_005f0.setParent(null);
      // /available-vehicle.jsp(181,1) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_tag_005fforEach_005f0.setVar("vehicle");
      // /available-vehicle.jsp(181,1) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_tag_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/available-vehicle.jsp(181,1) '${availablevehicle}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${availablevehicle}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int[] _jspx_push_body_count_tag_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_tag_005fforEach_005f0 = _jspx_th_tag_005fforEach_005f0.doStartTag();
        if (_jspx_eval_tag_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("    \n");
            out.write("          <div class=\"col-md-4 col-sm-6\">\n");
            out.write("          \n");
            out.write("            <div class=\"card mb-30\"><a class=\"card-img-tiles cb\" href=\"#\" data-abc=\"true\">\n");
            out.write("        \n");
            out.write("         \n");
            out.write("                <div class=\"inner\">\n");
            out.write("                \n");
            out.write("                </div></a>\n");
            out.write("              <div class=\"card-body text-center cb\">\n");
            out.write("                             \n");
            out.write("            <table>\n");
            out.write("	<tr>\n");
            out.write("	<td rowspan=\"5\">	\n");
            out.write("       ");
            if (_jspx_meth_tag_005fset_005f0(_jspx_th_tag_005fforEach_005f0, _jspx_page_context, _jspx_push_body_count_tag_005fforEach_005f0))
              return true;
            out.write("\n");
            out.write("          ");
            if (_jspx_meth_tag_005fif_005f0(_jspx_th_tag_005fforEach_005f0, _jspx_page_context, _jspx_push_body_count_tag_005fforEach_005f0))
              return true;
            out.write("\n");
            out.write("       ");
            if (_jspx_meth_tag_005fif_005f1(_jspx_th_tag_005fforEach_005f0, _jspx_page_context, _jspx_push_body_count_tag_005fforEach_005f0))
              return true;
            out.write("\n");
            out.write("         ");
            if (_jspx_meth_tag_005fif_005f2(_jspx_th_tag_005fforEach_005f0, _jspx_page_context, _jspx_push_body_count_tag_005fforEach_005f0))
              return true;
            out.write("\n");
            out.write("     \n");
            out.write("   \n");
            out.write("     </td>\n");
            out.write("	</tr>\n");
            out.write("	<tr>\n");
            out.write("	  <td class=\"x\"> ");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${vehicle.getVehicle_Model()}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\n");
            out.write("	\n");
            out.write("	</tr>\n");
            out.write("	\n");
            out.write("	<tr>\n");
            out.write("     	<td class=\"x\">Seat -");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${vehicle.getNumberof_Seat()}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write(" </td>\n");
            out.write("\n");
            out.write("\n");
            out.write("     </tr>\n");
            out.write("     \n");
            out.write("     <tr>\n");
            out.write("     	<td class=\"x\">Cost Per KM -");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${vehicle.getCostper_Km()}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write(" </td>\n");
            out.write("\n");
            out.write("\n");
            out.write("     </tr>\n");
            out.write("     \n");
            out.write("     <tr>\n");
            out.write("     	<td class=\"x\">\n");
            out.write("     	<form action=\"bookingData\" method=\"post\">\n");
            out.write("     	<input type=\"hidden\" name=\"action\" value=\"bookingData\">\n");
            out.write("     	<input type=\"hidden\" name=\"vehicleid\" value=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${vehicle. getVehicleID()}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\">\n");
            out.write("     	<input type=\"hidden\" name=\"kmcost\" value=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${vehicle.getCostper_Km()}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\">\n");
            out.write("     	\n");
            out.write("     	 <button type=\"submit\" class=\"btn btn-primary\">Book Now</button>\n");
            out.write("     	</form>\n");
            out.write("     	</td>\n");
            out.write("         \n");
            out.write("\n");
            out.write("     </tr>\n");
            out.write("\n");
            out.write("\n");
            out.write("\n");
            out.write("</table>\n");
            out.write("              \n");
            out.write("               </div>\n");
            out.write("            </div>\n");
            out.write("\n");
            out.write("            \n");
            out.write("          </div>\n");
            out.write("          \n");
            out.write("            ");
            int evalDoAfterBody = _jspx_th_tag_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_tag_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_tag_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_tag_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_tag_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005ftag_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_tag_005fforEach_005f0);
      _jspx_th_tag_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_tag_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_tag_005fforEach_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_tag_005fset_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_tag_005fforEach_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_tag_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  tag:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_tag_005fset_005f0 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005ftag_005fset_0026_005fvar_005fvalue_005fscope_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_tag_005fset_005f0_reused = false;
    try {
      _jspx_th_tag_005fset_005f0.setPageContext(_jspx_page_context);
      _jspx_th_tag_005fset_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_tag_005fforEach_005f0);
      // /available-vehicle.jsp(195,7) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_tag_005fset_005f0.setVar("type");
      // /available-vehicle.jsp(195,7) name = scope type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_tag_005fset_005f0.setScope("session");
      // /available-vehicle.jsp(195,7) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_tag_005fset_005f0.setValue(new org.apache.jasper.el.JspValueExpression("/available-vehicle.jsp(195,7) '${vehicle.getVehicle_Type()}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${vehicle.getVehicle_Type()}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int _jspx_eval_tag_005fset_005f0 = _jspx_th_tag_005fset_005f0.doStartTag();
      if (_jspx_th_tag_005fset_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005ftag_005fset_0026_005fvar_005fvalue_005fscope_005fnobody.reuse(_jspx_th_tag_005fset_005f0);
      _jspx_th_tag_005fset_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_tag_005fset_005f0, _jsp_getInstanceManager(), _jspx_th_tag_005fset_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_tag_005fif_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_tag_005fforEach_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_tag_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  tag:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_tag_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005ftag_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_tag_005fif_005f0_reused = false;
    try {
      _jspx_th_tag_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_tag_005fif_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_tag_005fforEach_005f0);
      // /available-vehicle.jsp(196,10) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_tag_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${type=='bus'}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_tag_005fif_005f0 = _jspx_th_tag_005fif_005f0.doStartTag();
      if (_jspx_eval_tag_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("             <img src=\"https://illustoon.com/photo/dl/5901.png\" width=\"150\" height=\"150\">\n");
          out.write("          ");
          int evalDoAfterBody = _jspx_th_tag_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_tag_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005ftag_005fif_0026_005ftest.reuse(_jspx_th_tag_005fif_005f0);
      _jspx_th_tag_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_tag_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_tag_005fif_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_tag_005fif_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_tag_005fforEach_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_tag_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  tag:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_tag_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005ftag_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_tag_005fif_005f1_reused = false;
    try {
      _jspx_th_tag_005fif_005f1.setPageContext(_jspx_page_context);
      _jspx_th_tag_005fif_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_tag_005fforEach_005f0);
      // /available-vehicle.jsp(199,7) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_tag_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${type=='van'}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_tag_005fif_005f1 = _jspx_th_tag_005fif_005f1.doStartTag();
      if (_jspx_eval_tag_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("                   <img src=\"https://illustoon.com/photo/dl/492.png\" width=\"150\" height=\"150\">\n");
          out.write("          ");
          int evalDoAfterBody = _jspx_th_tag_005fif_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_tag_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005ftag_005fif_0026_005ftest.reuse(_jspx_th_tag_005fif_005f1);
      _jspx_th_tag_005fif_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_tag_005fif_005f1, _jsp_getInstanceManager(), _jspx_th_tag_005fif_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_tag_005fif_005f2(javax.servlet.jsp.tagext.JspTag _jspx_th_tag_005fforEach_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_tag_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  tag:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_tag_005fif_005f2 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005ftag_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_tag_005fif_005f2_reused = false;
    try {
      _jspx_th_tag_005fif_005f2.setPageContext(_jspx_page_context);
      _jspx_th_tag_005fif_005f2.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_tag_005fforEach_005f0);
      // /available-vehicle.jsp(202,9) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_tag_005fif_005f2.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${type=='car'}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_tag_005fif_005f2 = _jspx_th_tag_005fif_005f2.doStartTag();
      if (_jspx_eval_tag_005fif_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("             <img src=\"https://illustoon.com/photo/dl/1741.png\" width=\"150\" height=\"150\">\n");
          out.write("          ");
          int evalDoAfterBody = _jspx_th_tag_005fif_005f2.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_tag_005fif_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005ftag_005fif_0026_005ftest.reuse(_jspx_th_tag_005fif_005f2);
      _jspx_th_tag_005fif_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_tag_005fif_005f2, _jsp_getInstanceManager(), _jspx_th_tag_005fif_005f2_reused);
    }
    return false;
  }
}
