/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.65
 * Generated at: 2022-09-15 07:09:37 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class booking_002dvehicle_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/T:/Tempory%20Data/Web%20App/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/go-cheeta/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153365282000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1660112728163L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write(" \r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"ISO-8859-1\">\r\n");
      out.write("    <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css\" rel=\"stylesheet\"/>\r\n");
      out.write("     <link rel=\"stylesheet\" href=\"css/addmin-dashboard-side.css\" />\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\" />\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css\"/>\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/booking-style.css\" />\r\n");
      out.write("<style>\r\n");
      out.write("body{\r\n");
      out.write("       background-image: url(\"image/bookingbg.jpeg\");\r\n");
      out.write("       background-size: auto; \r\n");
      out.write("       background-repeat: repeat;}\r\n");
      out.write("        \r\n");
      out.write(".row-data{\r\n");
      out.write("\r\n");
      out.write("Display:flex;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".row-data input,.row-data label{\r\n");
      out.write(" margin-left:40px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".row-web input,.row-web textarea,.row-web select{\r\n");
      out.write("  width:90%;\r\n");
      out.write("  margin-left:40px;\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(".row-web table tr th{\r\n");
      out.write("\r\n");
      out.write("margin-left:600%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".head-data{\r\n");
      out.write("margin-left:40px;\r\n");
      out.write("margin-bottom:20px;\r\n");
      out.write("color:white;\r\n");
      out.write("font-weight:bold;\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(".cent{\r\n");
      out.write("\r\n");
      out.write("margin-top:40px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(".row-button{\r\n");
      out.write("width:40%;\r\n");
      out.write("margin-left:40px;\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("label{\r\n");
      out.write("color:white;}\r\n");
      out.write("\r\n");
      out.write("row-data .spc{\r\n");
      out.write("margin-left:20px;\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("row-data .spc label{\r\n");
      out.write("margin-left:0px;\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".km{\r\n");
      out.write("\r\n");
      out.write("width:40px%;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("<title>Booking Vehicle</title>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<body >\r\n");


if((String) session.getAttribute("user")==null&&session.getAttribute("customerid")==null){
	
	response.sendRedirect("customer-login.jsp");
}



      out.write("\r\n");
      out.write("<div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "customer-navbar.jsp", out, false);
      out.write("\r\n");
      out.write(" <div class=\"d-flex justify-content-center cent\">\r\n");
      out.write("   <form action=\"bookingVehicle\" method=\"post\">\r\n");
      out.write("   \r\n");
      out.write("   <div class=\"head-data\">BOOKING ORDER</div>\r\n");
      out.write("\r\n");
      out.write("  <div class=\"row-web\">\r\n");
      out.write(" <select class=\"form-select form-group\" aria-label=\"Default select example\" name=\"branch\" required>\r\n");
      out.write("  <option VALUE=\"\"><b>Select City</b></option>\r\n");
      out.write("  <option value=\"galle\">Galle</option>\r\n");
      out.write("  <option value=\"kandy\">Kandy</option>\r\n");
      out.write("  <option value=\"nugegoda\">Nugegoda</option>\r\n");
      out.write("  <option value=\"gampaha\">Gampaha</option>\r\n");
      out.write("  <option value=\"kurunegala\">Kurunegala</option>\r\n");
      out.write("    <option value=\"jaffna\">Jaffna</option>\r\n");
      out.write("\r\n");
      out.write("</select>\r\n");
      out.write(" \r\n");
      out.write("  </div><br>\r\n");
      out.write("  \r\n");
      out.write("  <div class=\"row-web\">\r\n");
      out.write("   <textarea  type=\"email\" rows=\"4\" placeholder=\"Location\" name=\"location\" required ></textarea>\r\n");
      out.write(" </div><br>\r\n");
      out.write("\r\n");
      out.write("   <div class=\"row-data spc\">\r\n");
      out.write("   \r\n");
      out.write("   <label>Start Date</label><input type=\"date\" name=\"startdate\" class=\"form-group\" required/>\r\n");
      out.write("  \r\n");
      out.write("     \r\n");
      out.write("    </div><br>\r\n");
      out.write("    <div class=\"row-data spc\">\r\n");
      out.write("   <label>End Date</label><input type=\"date\"  class=\"form-group\" name=\"enddate\" required/>\r\n");
      out.write("    </div><br>\r\n");
      out.write("    \r\n");
      out.write("    <div class=\"row-web\">\r\n");
      out.write("           <input type=\"number\" class=\"form-group km\" placeholder=\"KM\" min=\"5\" name=\"km\"  required/>\r\n");
      out.write("    \r\n");
      out.write(" </div><br><input type=\"hidden\" name=\"action\" value=\"bookingvehicle\">\r\n");
      out.write(" <input type=\"text\" name=\"ID\" value=\"");
      out.print( session.getAttribute("ID") );
      out.write("\">\r\n");
      out.write("  <input type=\"text\" name=\"customid\" value=\"");
      out.print( session.getAttribute("customerid") );
      out.write("\">\r\n");
      out.write(" <input type=\"text\" name=\"costkm\" value=\"");
      out.print( session.getAttribute("cost") );
      out.write("\">\r\n");
      out.write(" <div class=\"d-flex justify-content-center\">\r\n");
      out.write(" \r\n");
      out.write(" <div class=\"row-button\">\r\n");
      out.write(" \r\n");
      out.write("  <button type=\"submit\" class=\"btn btn-success addvehiclebtn\">Book Now</button></div></div>\r\n");
      out.write("   \r\n");
      out.write(" \r\n");
      out.write("   </form>\r\n");
      out.write("   \r\n");
      out.write("   \r\n");
      out.write("   \r\n");
      out.write(" </div>\r\n");
      out.write(" \r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
